export const DOGAPI_GET_BREEDS_IMAGE_RANDOM_READ =
  "DOGAPI_GET_BREEDS_IMAGE_RANDOM_READ"
export const DOGAPI_GET_BREEDS_IMAGE_RANDOM_READ_SUCCEEDED =
  "DOGAPI_GET_BREEDS_IMAGE_RANDOM_READ_SUCCEEDED"
export const DOGAPI_GET_BREEDS_IMAGE_RANDOM_READ_FAILED =
  "DOGAPI_GET_BREEDS_IMAGE_RANDOM_READ_FAILED"
export const API_V1_BOOKINGTRANSACTION_LIST = "API_V1_BOOKINGTRANSACTION_LIST"
export const API_V1_BOOKINGTRANSACTION_LIST_SUCCEEDED =
  "API_V1_BOOKINGTRANSACTION_LIST_SUCCEEDED"
export const API_V1_BOOKINGTRANSACTION_LIST_FAILED =
  "API_V1_BOOKINGTRANSACTION_LIST_FAILED"
export const API_V1_BOOKINGTRANSACTION_CREATE =
  "API_V1_BOOKINGTRANSACTION_CREATE"
export const API_V1_BOOKINGTRANSACTION_CREATE_SUCCEEDED =
  "API_V1_BOOKINGTRANSACTION_CREATE_SUCCEEDED"
export const API_V1_BOOKINGTRANSACTION_CREATE_FAILED =
  "API_V1_BOOKINGTRANSACTION_CREATE_FAILED"
export const API_V1_BOOKINGTRANSACTION_READ = "API_V1_BOOKINGTRANSACTION_READ"
export const API_V1_BOOKINGTRANSACTION_READ_SUCCEEDED =
  "API_V1_BOOKINGTRANSACTION_READ_SUCCEEDED"
export const API_V1_BOOKINGTRANSACTION_READ_FAILED =
  "API_V1_BOOKINGTRANSACTION_READ_FAILED"
export const API_V1_BOOKINGTRANSACTION_UPDATE =
  "API_V1_BOOKINGTRANSACTION_UPDATE"
export const API_V1_BOOKINGTRANSACTION_UPDATE_SUCCEEDED =
  "API_V1_BOOKINGTRANSACTION_UPDATE_SUCCEEDED"
export const API_V1_BOOKINGTRANSACTION_UPDATE_FAILED =
  "API_V1_BOOKINGTRANSACTION_UPDATE_FAILED"
export const API_V1_BOOKINGTRANSACTION_PARTIAL_UPDATE =
  "API_V1_BOOKINGTRANSACTION_PARTIAL_UPDATE"
export const API_V1_BOOKINGTRANSACTION_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_BOOKINGTRANSACTION_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_BOOKINGTRANSACTION_PARTIAL_UPDATE_FAILED =
  "API_V1_BOOKINGTRANSACTION_PARTIAL_UPDATE_FAILED"
export const API_V1_BOOKINGTRANSACTION_DELETE =
  "API_V1_BOOKINGTRANSACTION_DELETE"
export const API_V1_BOOKINGTRANSACTION_DELETE_SUCCEEDED =
  "API_V1_BOOKINGTRANSACTION_DELETE_SUCCEEDED"
export const API_V1_BOOKINGTRANSACTION_DELETE_FAILED =
  "API_V1_BOOKINGTRANSACTION_DELETE_FAILED"
export const API_V1_CUSTOMTEXT_LIST = "API_V1_CUSTOMTEXT_LIST"
export const API_V1_CUSTOMTEXT_LIST_SUCCEEDED =
  "API_V1_CUSTOMTEXT_LIST_SUCCEEDED"
export const API_V1_CUSTOMTEXT_LIST_FAILED = "API_V1_CUSTOMTEXT_LIST_FAILED"
export const API_V1_CUSTOMTEXT_READ = "API_V1_CUSTOMTEXT_READ"
export const API_V1_CUSTOMTEXT_READ_SUCCEEDED =
  "API_V1_CUSTOMTEXT_READ_SUCCEEDED"
export const API_V1_CUSTOMTEXT_READ_FAILED = "API_V1_CUSTOMTEXT_READ_FAILED"
export const API_V1_CUSTOMTEXT_UPDATE = "API_V1_CUSTOMTEXT_UPDATE"
export const API_V1_CUSTOMTEXT_UPDATE_SUCCEEDED =
  "API_V1_CUSTOMTEXT_UPDATE_SUCCEEDED"
export const API_V1_CUSTOMTEXT_UPDATE_FAILED = "API_V1_CUSTOMTEXT_UPDATE_FAILED"
export const API_V1_CUSTOMTEXT_PARTIAL_UPDATE =
  "API_V1_CUSTOMTEXT_PARTIAL_UPDATE"
export const API_V1_CUSTOMTEXT_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_CUSTOMTEXT_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_CUSTOMTEXT_PARTIAL_UPDATE_FAILED =
  "API_V1_CUSTOMTEXT_PARTIAL_UPDATE_FAILED"
export const API_V1_DOCUMENT_LIST = "API_V1_DOCUMENT_LIST"
export const API_V1_DOCUMENT_LIST_SUCCEEDED = "API_V1_DOCUMENT_LIST_SUCCEEDED"
export const API_V1_DOCUMENT_LIST_FAILED = "API_V1_DOCUMENT_LIST_FAILED"
export const API_V1_DOCUMENT_CREATE = "API_V1_DOCUMENT_CREATE"
export const API_V1_DOCUMENT_CREATE_SUCCEEDED =
  "API_V1_DOCUMENT_CREATE_SUCCEEDED"
export const API_V1_DOCUMENT_CREATE_FAILED = "API_V1_DOCUMENT_CREATE_FAILED"
export const API_V1_DOCUMENT_READ = "API_V1_DOCUMENT_READ"
export const API_V1_DOCUMENT_READ_SUCCEEDED = "API_V1_DOCUMENT_READ_SUCCEEDED"
export const API_V1_DOCUMENT_READ_FAILED = "API_V1_DOCUMENT_READ_FAILED"
export const API_V1_DOCUMENT_UPDATE = "API_V1_DOCUMENT_UPDATE"
export const API_V1_DOCUMENT_UPDATE_SUCCEEDED =
  "API_V1_DOCUMENT_UPDATE_SUCCEEDED"
export const API_V1_DOCUMENT_UPDATE_FAILED = "API_V1_DOCUMENT_UPDATE_FAILED"
export const API_V1_DOCUMENT_PARTIAL_UPDATE = "API_V1_DOCUMENT_PARTIAL_UPDATE"
export const API_V1_DOCUMENT_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_DOCUMENT_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_DOCUMENT_PARTIAL_UPDATE_FAILED =
  "API_V1_DOCUMENT_PARTIAL_UPDATE_FAILED"
export const API_V1_DOCUMENT_DELETE = "API_V1_DOCUMENT_DELETE"
export const API_V1_DOCUMENT_DELETE_SUCCEEDED =
  "API_V1_DOCUMENT_DELETE_SUCCEEDED"
export const API_V1_DOCUMENT_DELETE_FAILED = "API_V1_DOCUMENT_DELETE_FAILED"
export const API_V1_DRIVERPROFILE_LIST = "API_V1_DRIVERPROFILE_LIST"
export const API_V1_DRIVERPROFILE_LIST_SUCCEEDED =
  "API_V1_DRIVERPROFILE_LIST_SUCCEEDED"
export const API_V1_DRIVERPROFILE_LIST_FAILED =
  "API_V1_DRIVERPROFILE_LIST_FAILED"
export const API_V1_DRIVERPROFILE_CREATE = "API_V1_DRIVERPROFILE_CREATE"
export const API_V1_DRIVERPROFILE_CREATE_SUCCEEDED =
  "API_V1_DRIVERPROFILE_CREATE_SUCCEEDED"
export const API_V1_DRIVERPROFILE_CREATE_FAILED =
  "API_V1_DRIVERPROFILE_CREATE_FAILED"
export const API_V1_DRIVERPROFILE_READ = "API_V1_DRIVERPROFILE_READ"
export const API_V1_DRIVERPROFILE_READ_SUCCEEDED =
  "API_V1_DRIVERPROFILE_READ_SUCCEEDED"
export const API_V1_DRIVERPROFILE_READ_FAILED =
  "API_V1_DRIVERPROFILE_READ_FAILED"
export const API_V1_DRIVERPROFILE_UPDATE = "API_V1_DRIVERPROFILE_UPDATE"
export const API_V1_DRIVERPROFILE_UPDATE_SUCCEEDED =
  "API_V1_DRIVERPROFILE_UPDATE_SUCCEEDED"
export const API_V1_DRIVERPROFILE_UPDATE_FAILED =
  "API_V1_DRIVERPROFILE_UPDATE_FAILED"
export const API_V1_DRIVERPROFILE_PARTIAL_UPDATE =
  "API_V1_DRIVERPROFILE_PARTIAL_UPDATE"
export const API_V1_DRIVERPROFILE_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_DRIVERPROFILE_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_DRIVERPROFILE_PARTIAL_UPDATE_FAILED =
  "API_V1_DRIVERPROFILE_PARTIAL_UPDATE_FAILED"
export const API_V1_DRIVERPROFILE_DELETE = "API_V1_DRIVERPROFILE_DELETE"
export const API_V1_DRIVERPROFILE_DELETE_SUCCEEDED =
  "API_V1_DRIVERPROFILE_DELETE_SUCCEEDED"
export const API_V1_DRIVERPROFILE_DELETE_FAILED =
  "API_V1_DRIVERPROFILE_DELETE_FAILED"
export const API_V1_DRIVERWALLET_LIST = "API_V1_DRIVERWALLET_LIST"
export const API_V1_DRIVERWALLET_LIST_SUCCEEDED =
  "API_V1_DRIVERWALLET_LIST_SUCCEEDED"
export const API_V1_DRIVERWALLET_LIST_FAILED = "API_V1_DRIVERWALLET_LIST_FAILED"
export const API_V1_DRIVERWALLET_CREATE = "API_V1_DRIVERWALLET_CREATE"
export const API_V1_DRIVERWALLET_CREATE_SUCCEEDED =
  "API_V1_DRIVERWALLET_CREATE_SUCCEEDED"
export const API_V1_DRIVERWALLET_CREATE_FAILED =
  "API_V1_DRIVERWALLET_CREATE_FAILED"
export const API_V1_DRIVERWALLET_READ = "API_V1_DRIVERWALLET_READ"
export const API_V1_DRIVERWALLET_READ_SUCCEEDED =
  "API_V1_DRIVERWALLET_READ_SUCCEEDED"
export const API_V1_DRIVERWALLET_READ_FAILED = "API_V1_DRIVERWALLET_READ_FAILED"
export const API_V1_DRIVERWALLET_UPDATE = "API_V1_DRIVERWALLET_UPDATE"
export const API_V1_DRIVERWALLET_UPDATE_SUCCEEDED =
  "API_V1_DRIVERWALLET_UPDATE_SUCCEEDED"
export const API_V1_DRIVERWALLET_UPDATE_FAILED =
  "API_V1_DRIVERWALLET_UPDATE_FAILED"
export const API_V1_DRIVERWALLET_PARTIAL_UPDATE =
  "API_V1_DRIVERWALLET_PARTIAL_UPDATE"
export const API_V1_DRIVERWALLET_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_DRIVERWALLET_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_DRIVERWALLET_PARTIAL_UPDATE_FAILED =
  "API_V1_DRIVERWALLET_PARTIAL_UPDATE_FAILED"
export const API_V1_DRIVERWALLET_DELETE = "API_V1_DRIVERWALLET_DELETE"
export const API_V1_DRIVERWALLET_DELETE_SUCCEEDED =
  "API_V1_DRIVERWALLET_DELETE_SUCCEEDED"
export const API_V1_DRIVERWALLET_DELETE_FAILED =
  "API_V1_DRIVERWALLET_DELETE_FAILED"
export const API_V1_HOMEPAGE_LIST = "API_V1_HOMEPAGE_LIST"
export const API_V1_HOMEPAGE_LIST_SUCCEEDED = "API_V1_HOMEPAGE_LIST_SUCCEEDED"
export const API_V1_HOMEPAGE_LIST_FAILED = "API_V1_HOMEPAGE_LIST_FAILED"
export const API_V1_HOMEPAGE_READ = "API_V1_HOMEPAGE_READ"
export const API_V1_HOMEPAGE_READ_SUCCEEDED = "API_V1_HOMEPAGE_READ_SUCCEEDED"
export const API_V1_HOMEPAGE_READ_FAILED = "API_V1_HOMEPAGE_READ_FAILED"
export const API_V1_HOMEPAGE_UPDATE = "API_V1_HOMEPAGE_UPDATE"
export const API_V1_HOMEPAGE_UPDATE_SUCCEEDED =
  "API_V1_HOMEPAGE_UPDATE_SUCCEEDED"
export const API_V1_HOMEPAGE_UPDATE_FAILED = "API_V1_HOMEPAGE_UPDATE_FAILED"
export const API_V1_HOMEPAGE_PARTIAL_UPDATE = "API_V1_HOMEPAGE_PARTIAL_UPDATE"
export const API_V1_HOMEPAGE_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_HOMEPAGE_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_HOMEPAGE_PARTIAL_UPDATE_FAILED =
  "API_V1_HOMEPAGE_PARTIAL_UPDATE_FAILED"
export const API_V1_INVITECODE_LIST = "API_V1_INVITECODE_LIST"
export const API_V1_INVITECODE_LIST_SUCCEEDED =
  "API_V1_INVITECODE_LIST_SUCCEEDED"
export const API_V1_INVITECODE_LIST_FAILED = "API_V1_INVITECODE_LIST_FAILED"
export const API_V1_INVITECODE_CREATE = "API_V1_INVITECODE_CREATE"
export const API_V1_INVITECODE_CREATE_SUCCEEDED =
  "API_V1_INVITECODE_CREATE_SUCCEEDED"
export const API_V1_INVITECODE_CREATE_FAILED = "API_V1_INVITECODE_CREATE_FAILED"
export const API_V1_INVITECODE_READ = "API_V1_INVITECODE_READ"
export const API_V1_INVITECODE_READ_SUCCEEDED =
  "API_V1_INVITECODE_READ_SUCCEEDED"
export const API_V1_INVITECODE_READ_FAILED = "API_V1_INVITECODE_READ_FAILED"
export const API_V1_INVITECODE_UPDATE = "API_V1_INVITECODE_UPDATE"
export const API_V1_INVITECODE_UPDATE_SUCCEEDED =
  "API_V1_INVITECODE_UPDATE_SUCCEEDED"
export const API_V1_INVITECODE_UPDATE_FAILED = "API_V1_INVITECODE_UPDATE_FAILED"
export const API_V1_INVITECODE_PARTIAL_UPDATE =
  "API_V1_INVITECODE_PARTIAL_UPDATE"
export const API_V1_INVITECODE_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_INVITECODE_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_INVITECODE_PARTIAL_UPDATE_FAILED =
  "API_V1_INVITECODE_PARTIAL_UPDATE_FAILED"
export const API_V1_INVITECODE_DELETE = "API_V1_INVITECODE_DELETE"
export const API_V1_INVITECODE_DELETE_SUCCEEDED =
  "API_V1_INVITECODE_DELETE_SUCCEEDED"
export const API_V1_INVITECODE_DELETE_FAILED = "API_V1_INVITECODE_DELETE_FAILED"
export const API_V1_LOGIN_CREATE = "API_V1_LOGIN_CREATE"
export const API_V1_LOGIN_CREATE_SUCCEEDED = "API_V1_LOGIN_CREATE_SUCCEEDED"
export const API_V1_LOGIN_CREATE_FAILED = "API_V1_LOGIN_CREATE_FAILED"
export const API_V1_MAPLOCATION_LIST = "API_V1_MAPLOCATION_LIST"
export const API_V1_MAPLOCATION_LIST_SUCCEEDED =
  "API_V1_MAPLOCATION_LIST_SUCCEEDED"
export const API_V1_MAPLOCATION_LIST_FAILED = "API_V1_MAPLOCATION_LIST_FAILED"
export const API_V1_MAPLOCATION_CREATE = "API_V1_MAPLOCATION_CREATE"
export const API_V1_MAPLOCATION_CREATE_SUCCEEDED =
  "API_V1_MAPLOCATION_CREATE_SUCCEEDED"
export const API_V1_MAPLOCATION_CREATE_FAILED =
  "API_V1_MAPLOCATION_CREATE_FAILED"
export const API_V1_MAPLOCATION_READ = "API_V1_MAPLOCATION_READ"
export const API_V1_MAPLOCATION_READ_SUCCEEDED =
  "API_V1_MAPLOCATION_READ_SUCCEEDED"
export const API_V1_MAPLOCATION_READ_FAILED = "API_V1_MAPLOCATION_READ_FAILED"
export const API_V1_MAPLOCATION_UPDATE = "API_V1_MAPLOCATION_UPDATE"
export const API_V1_MAPLOCATION_UPDATE_SUCCEEDED =
  "API_V1_MAPLOCATION_UPDATE_SUCCEEDED"
export const API_V1_MAPLOCATION_UPDATE_FAILED =
  "API_V1_MAPLOCATION_UPDATE_FAILED"
export const API_V1_MAPLOCATION_PARTIAL_UPDATE =
  "API_V1_MAPLOCATION_PARTIAL_UPDATE"
export const API_V1_MAPLOCATION_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_MAPLOCATION_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_MAPLOCATION_PARTIAL_UPDATE_FAILED =
  "API_V1_MAPLOCATION_PARTIAL_UPDATE_FAILED"
export const API_V1_MAPLOCATION_DELETE = "API_V1_MAPLOCATION_DELETE"
export const API_V1_MAPLOCATION_DELETE_SUCCEEDED =
  "API_V1_MAPLOCATION_DELETE_SUCCEEDED"
export const API_V1_MAPLOCATION_DELETE_FAILED =
  "API_V1_MAPLOCATION_DELETE_FAILED"
export const API_V1_MESSAGE_LIST = "API_V1_MESSAGE_LIST"
export const API_V1_MESSAGE_LIST_SUCCEEDED = "API_V1_MESSAGE_LIST_SUCCEEDED"
export const API_V1_MESSAGE_LIST_FAILED = "API_V1_MESSAGE_LIST_FAILED"
export const API_V1_MESSAGE_CREATE = "API_V1_MESSAGE_CREATE"
export const API_V1_MESSAGE_CREATE_SUCCEEDED = "API_V1_MESSAGE_CREATE_SUCCEEDED"
export const API_V1_MESSAGE_CREATE_FAILED = "API_V1_MESSAGE_CREATE_FAILED"
export const API_V1_MESSAGE_READ = "API_V1_MESSAGE_READ"
export const API_V1_MESSAGE_READ_SUCCEEDED = "API_V1_MESSAGE_READ_SUCCEEDED"
export const API_V1_MESSAGE_READ_FAILED = "API_V1_MESSAGE_READ_FAILED"
export const API_V1_MESSAGE_UPDATE = "API_V1_MESSAGE_UPDATE"
export const API_V1_MESSAGE_UPDATE_SUCCEEDED = "API_V1_MESSAGE_UPDATE_SUCCEEDED"
export const API_V1_MESSAGE_UPDATE_FAILED = "API_V1_MESSAGE_UPDATE_FAILED"
export const API_V1_MESSAGE_PARTIAL_UPDATE = "API_V1_MESSAGE_PARTIAL_UPDATE"
export const API_V1_MESSAGE_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_MESSAGE_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_MESSAGE_PARTIAL_UPDATE_FAILED =
  "API_V1_MESSAGE_PARTIAL_UPDATE_FAILED"
export const API_V1_MESSAGE_DELETE = "API_V1_MESSAGE_DELETE"
export const API_V1_MESSAGE_DELETE_SUCCEEDED = "API_V1_MESSAGE_DELETE_SUCCEEDED"
export const API_V1_MESSAGE_DELETE_FAILED = "API_V1_MESSAGE_DELETE_FAILED"
export const API_V1_NOTIFICATION_LIST = "API_V1_NOTIFICATION_LIST"
export const API_V1_NOTIFICATION_LIST_SUCCEEDED =
  "API_V1_NOTIFICATION_LIST_SUCCEEDED"
export const API_V1_NOTIFICATION_LIST_FAILED = "API_V1_NOTIFICATION_LIST_FAILED"
export const API_V1_NOTIFICATION_CREATE = "API_V1_NOTIFICATION_CREATE"
export const API_V1_NOTIFICATION_CREATE_SUCCEEDED =
  "API_V1_NOTIFICATION_CREATE_SUCCEEDED"
export const API_V1_NOTIFICATION_CREATE_FAILED =
  "API_V1_NOTIFICATION_CREATE_FAILED"
export const API_V1_NOTIFICATION_READ = "API_V1_NOTIFICATION_READ"
export const API_V1_NOTIFICATION_READ_SUCCEEDED =
  "API_V1_NOTIFICATION_READ_SUCCEEDED"
export const API_V1_NOTIFICATION_READ_FAILED = "API_V1_NOTIFICATION_READ_FAILED"
export const API_V1_NOTIFICATION_UPDATE = "API_V1_NOTIFICATION_UPDATE"
export const API_V1_NOTIFICATION_UPDATE_SUCCEEDED =
  "API_V1_NOTIFICATION_UPDATE_SUCCEEDED"
export const API_V1_NOTIFICATION_UPDATE_FAILED =
  "API_V1_NOTIFICATION_UPDATE_FAILED"
export const API_V1_NOTIFICATION_PARTIAL_UPDATE =
  "API_V1_NOTIFICATION_PARTIAL_UPDATE"
export const API_V1_NOTIFICATION_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_NOTIFICATION_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_NOTIFICATION_PARTIAL_UPDATE_FAILED =
  "API_V1_NOTIFICATION_PARTIAL_UPDATE_FAILED"
export const API_V1_NOTIFICATION_DELETE = "API_V1_NOTIFICATION_DELETE"
export const API_V1_NOTIFICATION_DELETE_SUCCEEDED =
  "API_V1_NOTIFICATION_DELETE_SUCCEEDED"
export const API_V1_NOTIFICATION_DELETE_FAILED =
  "API_V1_NOTIFICATION_DELETE_FAILED"
export const API_V1_PAYMENTMETHOD_LIST = "API_V1_PAYMENTMETHOD_LIST"
export const API_V1_PAYMENTMETHOD_LIST_SUCCEEDED =
  "API_V1_PAYMENTMETHOD_LIST_SUCCEEDED"
export const API_V1_PAYMENTMETHOD_LIST_FAILED =
  "API_V1_PAYMENTMETHOD_LIST_FAILED"
export const API_V1_PAYMENTMETHOD_CREATE = "API_V1_PAYMENTMETHOD_CREATE"
export const API_V1_PAYMENTMETHOD_CREATE_SUCCEEDED =
  "API_V1_PAYMENTMETHOD_CREATE_SUCCEEDED"
export const API_V1_PAYMENTMETHOD_CREATE_FAILED =
  "API_V1_PAYMENTMETHOD_CREATE_FAILED"
export const API_V1_PAYMENTMETHOD_READ = "API_V1_PAYMENTMETHOD_READ"
export const API_V1_PAYMENTMETHOD_READ_SUCCEEDED =
  "API_V1_PAYMENTMETHOD_READ_SUCCEEDED"
export const API_V1_PAYMENTMETHOD_READ_FAILED =
  "API_V1_PAYMENTMETHOD_READ_FAILED"
export const API_V1_PAYMENTMETHOD_UPDATE = "API_V1_PAYMENTMETHOD_UPDATE"
export const API_V1_PAYMENTMETHOD_UPDATE_SUCCEEDED =
  "API_V1_PAYMENTMETHOD_UPDATE_SUCCEEDED"
export const API_V1_PAYMENTMETHOD_UPDATE_FAILED =
  "API_V1_PAYMENTMETHOD_UPDATE_FAILED"
export const API_V1_PAYMENTMETHOD_PARTIAL_UPDATE =
  "API_V1_PAYMENTMETHOD_PARTIAL_UPDATE"
export const API_V1_PAYMENTMETHOD_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_PAYMENTMETHOD_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_PAYMENTMETHOD_PARTIAL_UPDATE_FAILED =
  "API_V1_PAYMENTMETHOD_PARTIAL_UPDATE_FAILED"
export const API_V1_PAYMENTMETHOD_DELETE = "API_V1_PAYMENTMETHOD_DELETE"
export const API_V1_PAYMENTMETHOD_DELETE_SUCCEEDED =
  "API_V1_PAYMENTMETHOD_DELETE_SUCCEEDED"
export const API_V1_PAYMENTMETHOD_DELETE_FAILED =
  "API_V1_PAYMENTMETHOD_DELETE_FAILED"
export const API_V1_PROFILELOCATION_LIST = "API_V1_PROFILELOCATION_LIST"
export const API_V1_PROFILELOCATION_LIST_SUCCEEDED =
  "API_V1_PROFILELOCATION_LIST_SUCCEEDED"
export const API_V1_PROFILELOCATION_LIST_FAILED =
  "API_V1_PROFILELOCATION_LIST_FAILED"
export const API_V1_PROFILELOCATION_CREATE = "API_V1_PROFILELOCATION_CREATE"
export const API_V1_PROFILELOCATION_CREATE_SUCCEEDED =
  "API_V1_PROFILELOCATION_CREATE_SUCCEEDED"
export const API_V1_PROFILELOCATION_CREATE_FAILED =
  "API_V1_PROFILELOCATION_CREATE_FAILED"
export const API_V1_PROFILELOCATION_READ = "API_V1_PROFILELOCATION_READ"
export const API_V1_PROFILELOCATION_READ_SUCCEEDED =
  "API_V1_PROFILELOCATION_READ_SUCCEEDED"
export const API_V1_PROFILELOCATION_READ_FAILED =
  "API_V1_PROFILELOCATION_READ_FAILED"
export const API_V1_PROFILELOCATION_UPDATE = "API_V1_PROFILELOCATION_UPDATE"
export const API_V1_PROFILELOCATION_UPDATE_SUCCEEDED =
  "API_V1_PROFILELOCATION_UPDATE_SUCCEEDED"
export const API_V1_PROFILELOCATION_UPDATE_FAILED =
  "API_V1_PROFILELOCATION_UPDATE_FAILED"
export const API_V1_PROFILELOCATION_PARTIAL_UPDATE =
  "API_V1_PROFILELOCATION_PARTIAL_UPDATE"
export const API_V1_PROFILELOCATION_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_PROFILELOCATION_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_PROFILELOCATION_PARTIAL_UPDATE_FAILED =
  "API_V1_PROFILELOCATION_PARTIAL_UPDATE_FAILED"
export const API_V1_PROFILELOCATION_DELETE = "API_V1_PROFILELOCATION_DELETE"
export const API_V1_PROFILELOCATION_DELETE_SUCCEEDED =
  "API_V1_PROFILELOCATION_DELETE_SUCCEEDED"
export const API_V1_PROFILELOCATION_DELETE_FAILED =
  "API_V1_PROFILELOCATION_DELETE_FAILED"
export const API_V1_RATING_LIST = "API_V1_RATING_LIST"
export const API_V1_RATING_LIST_SUCCEEDED = "API_V1_RATING_LIST_SUCCEEDED"
export const API_V1_RATING_LIST_FAILED = "API_V1_RATING_LIST_FAILED"
export const API_V1_RATING_CREATE = "API_V1_RATING_CREATE"
export const API_V1_RATING_CREATE_SUCCEEDED = "API_V1_RATING_CREATE_SUCCEEDED"
export const API_V1_RATING_CREATE_FAILED = "API_V1_RATING_CREATE_FAILED"
export const API_V1_RATING_READ = "API_V1_RATING_READ"
export const API_V1_RATING_READ_SUCCEEDED = "API_V1_RATING_READ_SUCCEEDED"
export const API_V1_RATING_READ_FAILED = "API_V1_RATING_READ_FAILED"
export const API_V1_RATING_UPDATE = "API_V1_RATING_UPDATE"
export const API_V1_RATING_UPDATE_SUCCEEDED = "API_V1_RATING_UPDATE_SUCCEEDED"
export const API_V1_RATING_UPDATE_FAILED = "API_V1_RATING_UPDATE_FAILED"
export const API_V1_RATING_PARTIAL_UPDATE = "API_V1_RATING_PARTIAL_UPDATE"
export const API_V1_RATING_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_RATING_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_RATING_PARTIAL_UPDATE_FAILED =
  "API_V1_RATING_PARTIAL_UPDATE_FAILED"
export const API_V1_RATING_DELETE = "API_V1_RATING_DELETE"
export const API_V1_RATING_DELETE_SUCCEEDED = "API_V1_RATING_DELETE_SUCCEEDED"
export const API_V1_RATING_DELETE_FAILED = "API_V1_RATING_DELETE_FAILED"
export const API_V1_SIGNUP_CREATE = "API_V1_SIGNUP_CREATE"
export const API_V1_SIGNUP_CREATE_SUCCEEDED = "API_V1_SIGNUP_CREATE_SUCCEEDED"
export const API_V1_SIGNUP_CREATE_FAILED = "API_V1_SIGNUP_CREATE_FAILED"
export const API_V1_USERPROFILE_LIST = "API_V1_USERPROFILE_LIST"
export const API_V1_USERPROFILE_LIST_SUCCEEDED =
  "API_V1_USERPROFILE_LIST_SUCCEEDED"
export const API_V1_USERPROFILE_LIST_FAILED = "API_V1_USERPROFILE_LIST_FAILED"
export const API_V1_USERPROFILE_CREATE = "API_V1_USERPROFILE_CREATE"
export const API_V1_USERPROFILE_CREATE_SUCCEEDED =
  "API_V1_USERPROFILE_CREATE_SUCCEEDED"
export const API_V1_USERPROFILE_CREATE_FAILED =
  "API_V1_USERPROFILE_CREATE_FAILED"
export const API_V1_USERPROFILE_READ = "API_V1_USERPROFILE_READ"
export const API_V1_USERPROFILE_READ_SUCCEEDED =
  "API_V1_USERPROFILE_READ_SUCCEEDED"
export const API_V1_USERPROFILE_READ_FAILED = "API_V1_USERPROFILE_READ_FAILED"
export const API_V1_USERPROFILE_UPDATE = "API_V1_USERPROFILE_UPDATE"
export const API_V1_USERPROFILE_UPDATE_SUCCEEDED =
  "API_V1_USERPROFILE_UPDATE_SUCCEEDED"
export const API_V1_USERPROFILE_UPDATE_FAILED =
  "API_V1_USERPROFILE_UPDATE_FAILED"
export const API_V1_USERPROFILE_PARTIAL_UPDATE =
  "API_V1_USERPROFILE_PARTIAL_UPDATE"
export const API_V1_USERPROFILE_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_USERPROFILE_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_USERPROFILE_PARTIAL_UPDATE_FAILED =
  "API_V1_USERPROFILE_PARTIAL_UPDATE_FAILED"
export const API_V1_USERPROFILE_DELETE = "API_V1_USERPROFILE_DELETE"
export const API_V1_USERPROFILE_DELETE_SUCCEEDED =
  "API_V1_USERPROFILE_DELETE_SUCCEEDED"
export const API_V1_USERPROFILE_DELETE_FAILED =
  "API_V1_USERPROFILE_DELETE_FAILED"
export const API_V1_USERWALLET_LIST = "API_V1_USERWALLET_LIST"
export const API_V1_USERWALLET_LIST_SUCCEEDED =
  "API_V1_USERWALLET_LIST_SUCCEEDED"
export const API_V1_USERWALLET_LIST_FAILED = "API_V1_USERWALLET_LIST_FAILED"
export const API_V1_USERWALLET_CREATE = "API_V1_USERWALLET_CREATE"
export const API_V1_USERWALLET_CREATE_SUCCEEDED =
  "API_V1_USERWALLET_CREATE_SUCCEEDED"
export const API_V1_USERWALLET_CREATE_FAILED = "API_V1_USERWALLET_CREATE_FAILED"
export const API_V1_USERWALLET_READ = "API_V1_USERWALLET_READ"
export const API_V1_USERWALLET_READ_SUCCEEDED =
  "API_V1_USERWALLET_READ_SUCCEEDED"
export const API_V1_USERWALLET_READ_FAILED = "API_V1_USERWALLET_READ_FAILED"
export const API_V1_USERWALLET_UPDATE = "API_V1_USERWALLET_UPDATE"
export const API_V1_USERWALLET_UPDATE_SUCCEEDED =
  "API_V1_USERWALLET_UPDATE_SUCCEEDED"
export const API_V1_USERWALLET_UPDATE_FAILED = "API_V1_USERWALLET_UPDATE_FAILED"
export const API_V1_USERWALLET_PARTIAL_UPDATE =
  "API_V1_USERWALLET_PARTIAL_UPDATE"
export const API_V1_USERWALLET_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_USERWALLET_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_USERWALLET_PARTIAL_UPDATE_FAILED =
  "API_V1_USERWALLET_PARTIAL_UPDATE_FAILED"
export const API_V1_USERWALLET_DELETE = "API_V1_USERWALLET_DELETE"
export const API_V1_USERWALLET_DELETE_SUCCEEDED =
  "API_V1_USERWALLET_DELETE_SUCCEEDED"
export const API_V1_USERWALLET_DELETE_FAILED = "API_V1_USERWALLET_DELETE_FAILED"
export const API_V1_VEHICLE_LIST = "API_V1_VEHICLE_LIST"
export const API_V1_VEHICLE_LIST_SUCCEEDED = "API_V1_VEHICLE_LIST_SUCCEEDED"
export const API_V1_VEHICLE_LIST_FAILED = "API_V1_VEHICLE_LIST_FAILED"
export const API_V1_VEHICLE_CREATE = "API_V1_VEHICLE_CREATE"
export const API_V1_VEHICLE_CREATE_SUCCEEDED = "API_V1_VEHICLE_CREATE_SUCCEEDED"
export const API_V1_VEHICLE_CREATE_FAILED = "API_V1_VEHICLE_CREATE_FAILED"
export const API_V1_VEHICLE_READ = "API_V1_VEHICLE_READ"
export const API_V1_VEHICLE_READ_SUCCEEDED = "API_V1_VEHICLE_READ_SUCCEEDED"
export const API_V1_VEHICLE_READ_FAILED = "API_V1_VEHICLE_READ_FAILED"
export const API_V1_VEHICLE_UPDATE = "API_V1_VEHICLE_UPDATE"
export const API_V1_VEHICLE_UPDATE_SUCCEEDED = "API_V1_VEHICLE_UPDATE_SUCCEEDED"
export const API_V1_VEHICLE_UPDATE_FAILED = "API_V1_VEHICLE_UPDATE_FAILED"
export const API_V1_VEHICLE_PARTIAL_UPDATE = "API_V1_VEHICLE_PARTIAL_UPDATE"
export const API_V1_VEHICLE_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_VEHICLE_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_VEHICLE_PARTIAL_UPDATE_FAILED =
  "API_V1_VEHICLE_PARTIAL_UPDATE_FAILED"
export const API_V1_VEHICLE_DELETE = "API_V1_VEHICLE_DELETE"
export const API_V1_VEHICLE_DELETE_SUCCEEDED = "API_V1_VEHICLE_DELETE_SUCCEEDED"
export const API_V1_VEHICLE_DELETE_FAILED = "API_V1_VEHICLE_DELETE_FAILED"
export const API_V1_VEHICLELOCATION_LIST = "API_V1_VEHICLELOCATION_LIST"
export const API_V1_VEHICLELOCATION_LIST_SUCCEEDED =
  "API_V1_VEHICLELOCATION_LIST_SUCCEEDED"
export const API_V1_VEHICLELOCATION_LIST_FAILED =
  "API_V1_VEHICLELOCATION_LIST_FAILED"
export const API_V1_VEHICLELOCATION_CREATE = "API_V1_VEHICLELOCATION_CREATE"
export const API_V1_VEHICLELOCATION_CREATE_SUCCEEDED =
  "API_V1_VEHICLELOCATION_CREATE_SUCCEEDED"
export const API_V1_VEHICLELOCATION_CREATE_FAILED =
  "API_V1_VEHICLELOCATION_CREATE_FAILED"
export const API_V1_VEHICLELOCATION_READ = "API_V1_VEHICLELOCATION_READ"
export const API_V1_VEHICLELOCATION_READ_SUCCEEDED =
  "API_V1_VEHICLELOCATION_READ_SUCCEEDED"
export const API_V1_VEHICLELOCATION_READ_FAILED =
  "API_V1_VEHICLELOCATION_READ_FAILED"
export const API_V1_VEHICLELOCATION_UPDATE = "API_V1_VEHICLELOCATION_UPDATE"
export const API_V1_VEHICLELOCATION_UPDATE_SUCCEEDED =
  "API_V1_VEHICLELOCATION_UPDATE_SUCCEEDED"
export const API_V1_VEHICLELOCATION_UPDATE_FAILED =
  "API_V1_VEHICLELOCATION_UPDATE_FAILED"
export const API_V1_VEHICLELOCATION_PARTIAL_UPDATE =
  "API_V1_VEHICLELOCATION_PARTIAL_UPDATE"
export const API_V1_VEHICLELOCATION_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_VEHICLELOCATION_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_VEHICLELOCATION_PARTIAL_UPDATE_FAILED =
  "API_V1_VEHICLELOCATION_PARTIAL_UPDATE_FAILED"
export const API_V1_VEHICLELOCATION_DELETE = "API_V1_VEHICLELOCATION_DELETE"
export const API_V1_VEHICLELOCATION_DELETE_SUCCEEDED =
  "API_V1_VEHICLELOCATION_DELETE_SUCCEEDED"
export const API_V1_VEHICLELOCATION_DELETE_FAILED =
  "API_V1_VEHICLELOCATION_DELETE_FAILED"
export const API_V1_VEHICLETYPE_LIST = "API_V1_VEHICLETYPE_LIST"
export const API_V1_VEHICLETYPE_LIST_SUCCEEDED =
  "API_V1_VEHICLETYPE_LIST_SUCCEEDED"
export const API_V1_VEHICLETYPE_LIST_FAILED = "API_V1_VEHICLETYPE_LIST_FAILED"
export const API_V1_VEHICLETYPE_CREATE = "API_V1_VEHICLETYPE_CREATE"
export const API_V1_VEHICLETYPE_CREATE_SUCCEEDED =
  "API_V1_VEHICLETYPE_CREATE_SUCCEEDED"
export const API_V1_VEHICLETYPE_CREATE_FAILED =
  "API_V1_VEHICLETYPE_CREATE_FAILED"
export const API_V1_VEHICLETYPE_READ = "API_V1_VEHICLETYPE_READ"
export const API_V1_VEHICLETYPE_READ_SUCCEEDED =
  "API_V1_VEHICLETYPE_READ_SUCCEEDED"
export const API_V1_VEHICLETYPE_READ_FAILED = "API_V1_VEHICLETYPE_READ_FAILED"
export const API_V1_VEHICLETYPE_UPDATE = "API_V1_VEHICLETYPE_UPDATE"
export const API_V1_VEHICLETYPE_UPDATE_SUCCEEDED =
  "API_V1_VEHICLETYPE_UPDATE_SUCCEEDED"
export const API_V1_VEHICLETYPE_UPDATE_FAILED =
  "API_V1_VEHICLETYPE_UPDATE_FAILED"
export const API_V1_VEHICLETYPE_PARTIAL_UPDATE =
  "API_V1_VEHICLETYPE_PARTIAL_UPDATE"
export const API_V1_VEHICLETYPE_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_VEHICLETYPE_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_VEHICLETYPE_PARTIAL_UPDATE_FAILED =
  "API_V1_VEHICLETYPE_PARTIAL_UPDATE_FAILED"
export const API_V1_VEHICLETYPE_DELETE = "API_V1_VEHICLETYPE_DELETE"
export const API_V1_VEHICLETYPE_DELETE_SUCCEEDED =
  "API_V1_VEHICLETYPE_DELETE_SUCCEEDED"
export const API_V1_VEHICLETYPE_DELETE_FAILED =
  "API_V1_VEHICLETYPE_DELETE_FAILED"
export const REST_AUTH_LOGIN_CREATE = "REST_AUTH_LOGIN_CREATE"
export const REST_AUTH_LOGIN_CREATE_SUCCEEDED =
  "REST_AUTH_LOGIN_CREATE_SUCCEEDED"
export const REST_AUTH_LOGIN_CREATE_FAILED = "REST_AUTH_LOGIN_CREATE_FAILED"
export const REST_AUTH_LOGOUT_LIST = "REST_AUTH_LOGOUT_LIST"
export const REST_AUTH_LOGOUT_LIST_SUCCEEDED = "REST_AUTH_LOGOUT_LIST_SUCCEEDED"
export const REST_AUTH_LOGOUT_LIST_FAILED = "REST_AUTH_LOGOUT_LIST_FAILED"
export const REST_AUTH_LOGOUT_CREATE = "REST_AUTH_LOGOUT_CREATE"
export const REST_AUTH_LOGOUT_CREATE_SUCCEEDED =
  "REST_AUTH_LOGOUT_CREATE_SUCCEEDED"
export const REST_AUTH_LOGOUT_CREATE_FAILED = "REST_AUTH_LOGOUT_CREATE_FAILED"
export const REST_AUTH_PASSWORD_CHANGE_CREATE =
  "REST_AUTH_PASSWORD_CHANGE_CREATE"
export const REST_AUTH_PASSWORD_CHANGE_CREATE_SUCCEEDED =
  "REST_AUTH_PASSWORD_CHANGE_CREATE_SUCCEEDED"
export const REST_AUTH_PASSWORD_CHANGE_CREATE_FAILED =
  "REST_AUTH_PASSWORD_CHANGE_CREATE_FAILED"
export const REST_AUTH_PASSWORD_RESET_CREATE = "REST_AUTH_PASSWORD_RESET_CREATE"
export const REST_AUTH_PASSWORD_RESET_CREATE_SUCCEEDED =
  "REST_AUTH_PASSWORD_RESET_CREATE_SUCCEEDED"
export const REST_AUTH_PASSWORD_RESET_CREATE_FAILED =
  "REST_AUTH_PASSWORD_RESET_CREATE_FAILED"
export const REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE =
  "REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE"
export const REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_SUCCEEDED =
  "REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_SUCCEEDED"
export const REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_FAILED =
  "REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_FAILED"
export const REST_AUTH_REGISTRATION_CREATE = "REST_AUTH_REGISTRATION_CREATE"
export const REST_AUTH_REGISTRATION_CREATE_SUCCEEDED =
  "REST_AUTH_REGISTRATION_CREATE_SUCCEEDED"
export const REST_AUTH_REGISTRATION_CREATE_FAILED =
  "REST_AUTH_REGISTRATION_CREATE_FAILED"
export const REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE =
  "REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE"
export const REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_SUCCEEDED =
  "REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_SUCCEEDED"
export const REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_FAILED =
  "REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_FAILED"
export const REST_AUTH_USER_READ = "REST_AUTH_USER_READ"
export const REST_AUTH_USER_READ_SUCCEEDED = "REST_AUTH_USER_READ_SUCCEEDED"
export const REST_AUTH_USER_READ_FAILED = "REST_AUTH_USER_READ_FAILED"
export const REST_AUTH_USER_UPDATE = "REST_AUTH_USER_UPDATE"
export const REST_AUTH_USER_UPDATE_SUCCEEDED = "REST_AUTH_USER_UPDATE_SUCCEEDED"
export const REST_AUTH_USER_UPDATE_FAILED = "REST_AUTH_USER_UPDATE_FAILED"
export const REST_AUTH_USER_PARTIAL_UPDATE = "REST_AUTH_USER_PARTIAL_UPDATE"
export const REST_AUTH_USER_PARTIAL_UPDATE_SUCCEEDED =
  "REST_AUTH_USER_PARTIAL_UPDATE_SUCCEEDED"
export const REST_AUTH_USER_PARTIAL_UPDATE_FAILED =
  "REST_AUTH_USER_PARTIAL_UPDATE_FAILED"
